pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "stylishy62/colorpl_admin"
        GIT_CREDENTIALS_ID = '0d1b1d1e-4f09-42a0-9c09-519c062b3fb5'
        DOCKER_CREDENTIALS_ID = 'docker_jenkins'
        SSH_CREDENTIALS_ID = 'ssh_public'
        REMOTE_USER = 'ubuntu'
        REMOTE_HOST = 'i11d109.p.ssafy.io'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'develop-web', credentialsId: "${GIT_CREDENTIALS_ID}", url: 'https://lab.ssafy.com/s11-webmobile4-sub2/S11P12D109.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build("${DOCKER_IMAGE}:${env.BUILD_ID}", "-f BE2/Dockerfile .")
                }
            }
        }

        stage('Test Docker Image') {
            steps {
                script {
                    dockerImage.inside {
                        sh 'pytest'
                    }
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', "${DOCKER_CREDENTIALS_ID}") {
                        dockerImage.push("${env.BUILD_ID}")
                        dockerImage.push("latest")
                    }
                }
            }
        }

        stage('Deploy to Remote Server') {
            steps {
                script {
                    sshagent(credentials: ["${SSH_CREDENTIALS_ID}"]) {
                        sh """
                        ssh ${REMOTE_USER}@${REMOTE_HOST} << EOF
                        docker rm -f fastapi-app || true
                        docker run -d --name fastapi-app -p 8000:8000 ${DOCKER_IMAGE}:${env.BUILD_ID}
                        EOF
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
